apiVersion: core.jenkins-x.io/v4beta1
kind: Requirements
spec:
  autoUpdate:
    enabled: false
    schedule: ""
  terraform: true
  cluster:
    devEnvApprovers:
    - todo
    clusterName: "apigw-eks"
    environmentGitOwner: ""
    gitKind: github
    gitName: github
    gitServer: https://github.com
    provider: eks
    region: "eu-west-1"
    registry: "206564425444.dkr.ecr.eu-west-1.amazonaws.com"
    project: "206564425444"
  environments:
  - key: dev
  - key: staging
  - key: production
  ingress:
    domain: ""
    ignoreLoadBalancer: false
    externalDNS: false
    namespaceSubDomain: -jx.
    tls:
      email: ""
      enabled: false
      production: false
  repository: nexus
  secretStorage: secretsManager
  vault: {}   
  storage:
  - name: backup
    enabled: false
  - name: logs
    enabled: true
    url: s3://logs-apigw-eks-20230321090204764600000001
  - name: reports
    enabled: true
    url: s3://reports-apigw-eks-20230321090204773300000005
  - name: repository
    enabled: true
    url: s3://repository-apigw-eks-20230321090204770600000003
  webhook: lighthouse
